language: ja-JP
reviews:
  profile: chill
  request_changes_workflow: true
  auto_review:
    drafts: true
    base_branches:
      - .*
knowledge_base:
  learnings:
    scope: local
  issues:
    scope: local
  pull_requests:
    scope: local
code_generation:
  docstrings:
    language: ja-JP
